finch_collector_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('world_cups/', views.worldcups_index, name='index'),
    path('world_cups/<int:cup_id>', views.worldcups_details, name='detail'),
    path('world_cups/create/',
         views.CupCreate.as_view(),
         name='world_cups_create'),
    path('world_cups/<int:pk>/update/',
         views.CupUpdate.as_view(),
         name='world_cups_update'),
    path('world_cups/<int:pk>/delete/',
         views.CupDelete.as_view(),
         name='world_cups_delete'),
    path('world_cups/<int:cup_id>/add_fan/', views.add_fan, name='add_fan'),
    path("world_cups/<int:cup_id>/assoc_attire/<int:item_id>/",
         views.assoc_attire,
         name="assoc_attire"),
    path("world_cups/<int:cup_id>/add_photo/",
         views.add_photo,
         name="add_photo"),
    path('items/', views.items_index, name='all_items'),
    path('items/<int:item_id>/', views.item_detail, name='item_detail'),
    path('items/create/', views.Create_item.as_view(), name='create_item'),
    path("items/<int:pk>/update/",
         views.Update_item.as_view(),
         name="update_item"),
    path("items/<int:pk>/delete/",
         views.Delete_item.as_view(),
         name="delete_item"),
]

main_app/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

ATTIRE = (('Hat', 'Hat'), ('Shirt', 'Shirt'), ('Pants', 'Pants'), ('None',
                                                                   'None'))


class FanAttire(models.Model):
    clothing = models.CharField(max_length=5,
                                choices=ATTIRE,
                                default=ATTIRE[3][0])
    description = models.TextField(max_length=150)

    def __str__(self):
        return f'{self.clothing} {self.description}'

    def get_absolute_url(self):
        return reverse("SportsParaphernalia_detail",
                       kwargs={"SportsParaphernalia_id": self.id})


class World_Cup(models.Model):
    location = models.CharField(max_length=40)
    year = models.IntegerField()
    champion = models.CharField(max_length=40)
    runner_up = models.CharField(max_length=40)
    mvps = models.TextField(max_length=255)
    champion_score = models.IntegerField()
    runner_up_score = models.IntegerField()
    fan_attire = models.ManyToManyField(FanAttire)

    def __str__(self):
        return self.location

    def get_absolute_url(self):
        return reverse('detail', kwargs={'cup_id': self.id})


PREFER = (('A', 'Team A'), ('B', 'Team B'))


class Fan(models.Model):
    name = models.CharField(max_length=40)
    age = models.IntegerField()
    country_of_residency = models.CharField('Country/Planet of Residence',
                                            max_length=20)
    supports = models.CharField(max_length=1,
                                choices=PREFER,
                                default=PREFER[0][0])

    world_cup = models.ForeignKey(World_Cup, on_delete=models.CASCADE)


class Photo(models.Model):
    url = models.CharField(max_length=200)
    world_cup = models.ForeignKey(World_Cup, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for world_cup_id: {self.world_cup_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Fan


class FanForm(ModelForm):
    class Meta:
        model = Fan
        fields = ['name', 'age', 'country_of_residency', 'supports']

main_app/views.py
from django.shortcuts import render, redirect
import uuid
import boto3
from .models import Photo, World_Cup, FanAttire
from .forms import FanForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView

S3_BASE_URL = "https://s3-us-east-2.amazonaws.com/"
BUCKET = "actualworldcup"

# Create your views here.


def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')


def worldcups_index(request):
    world_cups = World_Cup.objects.all()
    context = {'world_cups': world_cups}
    return render(request, 'world_cups/index.html', context)


def worldcups_details(request, cup_id):
    world_cup = World_Cup.objects.get(id=cup_id)
    fan_form = FanForm()
    attire_world_cup_fans = FanAttire.objects.exclude(
        id__in=world_cup.fan_attire.all().values_list('id'))
    context = {
        'cup': world_cup,
        'fan_form': fan_form,
        'items': attire_world_cup_fans
    }
    return render(request, 'world_cups/detail.html', context)


class CupCreate(CreateView):
    model = World_Cup
    fields = '__all__'


class CupUpdate(UpdateView):
    model = World_Cup
    fields = ['location', 'year', 'mvps']


class CupDelete(DeleteView):
    model = World_Cup
    success_url = '/world_cups/'


def add_fan(request, cup_id):
    form = FanForm(request.POST)
    if form.is_valid():
        new_fan = form.save(commit=False)
        new_fan.world_cup_id = cup_id
        new_fan.save()
    return redirect('detail', cup_id=cup_id)


def items_index(request):
    items = FanAttire.objects.all()
    context = {"items": items}

    return render(request, "item/index.html", context)


def item_detail(request, item_id):
    item = FanAttire.objects.get(id=item_id)
    context = {"item": item}
    return render(request, "item/detail.html", context)


class Create_item(CreateView):
    model = FanAttire
    fields = "__all__"


class Update_item(UpdateView):
    model = FanAttire
    fields = ["clothing", 'description']


class Delete_item(DeleteView):
    model = FanAttire
    success_url = "/items/"


def assoc_attire(request, cup_id, item_id):
    World_Cup.objects.get(id=cup_id).fan_attire.add(item_id)
    return redirect('detail', cup_id=cup_id)


def add_photo(request, cup_id):
    # photo-file will be the "name" attribute on the <input type="file">
    photo_file = request.FILES.get("photo-file", None)
    if photo_file:
        s3 = boto3.client("s3")
        # need a unique "key" for S3 / needs image file extension too
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind("."
                                                                           ):]
        # just in case something goes wrong
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            # build the full url string
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            # we can assign to cat_id or cat (if you have a cat object)
            photo = Photo(url=url, world_cup_id=cup_id)
            photo.save()
        except:
            print("An error occurred uploading file to S3")
    return redirect("detail", cup_id=cup_id)

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}

<h1>About WorldCup</h1>
<hrst />
<h5>Find out about different Football World Cups throughout history here!</h5>
<h5><a href="{% url 'index' %}">Click here</a> to find out more</h5>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>WorldCups</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    <header class="navbar-fixed">
      <nav class="teal lighten-2">
        <div class="nav-wrapper">
          <ul>
            <li><a href="/" class="left brand-logo">&nbsp;&nbsp;WorldCups</a></li>
          </ul>
          <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'world_cups_create' %}">Add a World Cup</a></li>
            <li><a href="{% url  'index' %}">View World Cups</a></li>
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer teal lighten-2">
      <div class="right">All Rights Reserved, &copy; 2021 WorldCups &nbsp;</div>
    </footer>
  </body>
</html>

main_app/templates/home.html
{% extends 'base.html' %} {% block content %}

<h1>Welcome to WorldCups!</h1>

{% endblock %}

main_app/templates/item/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Item Details</h1>

<div class="card">
  <div class="card-content">
    <span class="card-title">Summary of this fan's {{ item.clothing }}</span>
    <p>{{ item.description }}</p>
  </div>
  <div class="card-action">
    <a href="{% url 'update_item' item.id %}">Edit</a>
    <a href="{% url 'delete_item' item.id %}">Delete</a>
  </div>
</div>

{% endblock %}

main_app/templates/item/index.html
{% extends 'base.html' %} {% block content %} {% for item in items %}

<div class="card">
  <a href="{% url 'item_detail' item.id %}">
    <div class="card-content">
      <span class="card-title">This fan brought an interesting {{ item.clothing }}</span>
      <p>Clothing: {{ item.clothing }}</p>
      <p>Description: {{ item.description }}</p>
    </div>
  </a>
</div>
{% comment %} if there is no elemnts in our list will display no toys {% endcomment %} {% empty %}

<div class="card">
  <div class="card-content">
    <span class="card-title">No items</span>
  </div>
</div>

{% endfor %} {% endblock %}

main_app/templates/main_app/world_cup_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete World Cup</h1>

<h4>
  Are you sure you want to delete <span class="teal-text">{{ object.location }}</span> World Cup
  <span class="teal-text">{{ object.year }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'detail' world_cup.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/world_cup_form.html
{% extends 'base.html' %} {% block content %} {% if object %}
<h1>
  Edit <span class="teal-text">{{object.location}}</span> World Cup <span class="teal-text">{{object.year}}</span>
</h1>
{% else %}
<h1>Add World Cup</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="post">
  <!-- Django requires the following for security purposes -->
  {% csrf_token %}
  <table>
    <!-- Render the inputs inside of <tr>s & <td>s -->
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn" />
</form>
{% endblock %}

main_app/templates/world_cups/detail.html
{% extends 'base.html' %} {% block content %}

<h1>World Cup Details</h1>
<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">Cup Year: {{ cup.year }}</span>
        <h5>Location: {{ cup.location }}</h5>
        <h5>Match between:</h5>
        <h5>(A) {{ cup.champion }} v. {{ cup.runner_up }} (B)</h5>
        <br />
        <h5>Final Score:</h5>
        <h5>{{ cup.champion }} {{ cup.champion_score }} - {{ cup.runner_up_score }} {{ cup.runner_up}}</h5>
        <h5>MVP's</h5>
        <h5>{{ cup.mvps }}</h5>
      </div>
      <div class="card-action">
        <a href="{% url 'world_cups_update' cup.id %}">Edit</a>
        <a href="{% url 'world_cups_delete' cup.id %}">Delete</a>
      </div>
    </div>
    {% for photo in cup.photo_set.all %}
    <img class="responsive-img card-panel" src="{{photo.url}}" />
    {% empty %}
    <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}

    <form action="{% url 'add_photo' cup.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
      {% csrf_token %}
      <input type="file" name="photo-file" />
      <br /><br />
      <input type="submit" class="btn" value="Upload Photo" />
    </form>
  </div>
  <div class="col s6">
    <form action="{% url 'add_fan' cup.id %}" method="post">
      {% csrf_token %} {{ fan_form.as_p }}
      <input type="submit" class="btn" value="Add Fan" />
    </form>
    <h4>FANS</h4>
    <table class="striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Age</th>
          <th>From</th>
          <th>Supports</th>
        </tr>
      </thead>
      <tbody>
        {% for fan in cup.fan_set.all %}
        <tr>
          <td>{{fan.name}}</td>
          <td>{{fan.age}}</td>
          <td>{{fan.country_of_residency}}</td>
          {% if fan.get_supports_display == 'Team A' %}
          <td>{{cup.champion}}</td>
          {% else %}
          <td>{{cup.runner_up}}</td>
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<hr />
<div class="row">
  <div class="col s6">
    <h3>{{ cup.year }}'s World Cup Fan Attire</h3>
    {% if cup.fan_attire.count %} {% for attire in cup.fan_attire.all %}
    <div class="card">
      <a href="{% url 'item_detail' attire.id %}">
        <div class="card-content">
          <span class="card-title"> An interesting {{ attire.clothing }} </span>
        </div>
      </a>
    </div>
    {% endfor %} {% else %}
    <h5>No Fans are bringing fun clothing :(</h5>
    {% endif %}
  </div>
  <div class="col s6">
    <h3>Available Attire</h3>
    {% if items.count %} {% for item in items.all %}
    <div class="card">
      <a href="{% url 'item_detail' item.id %}">
        <div class="card-content">
          <span class="card-title"> An interesting {{ item.clothing }} </span>
        </div>
      </a>
      <div class="card-action">
        <form action="{% url 'assoc_attire' cup.id item.id %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn">Add</button>
        </form>
      </div>
    </div>
    {% endfor %} {% else %}
    <h5>All registered attire has been added for the {{ cup.year }} World Cup</h5>
    {% endif %}
  </div>
</div>

<script>
  var selectEl = document.getElementById("id_supports");
  M.FormSelect.init(selectEl);
</script>

{% endblock %}

main_app/templates/world_cups/index.html
{% extends 'base.html' %} {% block content %}

<h1>World Cup List</h1>

{% for cup in world_cups %}
<div class="card">
  <a href="{% url 'detail' cup.id %}">
    <div class="card-content">
      <span class="card-title">Cup Year: {{ cup.year }}</span>
      <h5>Location: {{ cup.location }}</h5>
      <h5>Match between:</h5>
      <h5>(A) {{ cup.champion }} v. {{ cup.runner_up }} (B)</h5>
      <br />
      <h5>Final Score:</h5>
      <h5>{{ cup.champion }} {{ cup.champion_score }} - {{ cup.runner_up_score }} {{ cup.runner_up}}</h5>
      <h5>MVP's</h5>
      <h5>{{ cup.mvps }}</h5>
    </div>
  </a>
</div>
{% endfor %} {% endblock %}